### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by runjak** [runjak/TranscriptionDesk#1]
We need to decide on a LICENSE file for our project. I believe @ThomasK81 said some Creative Common flavor would be preferred.

**Comment by ThomasK81** [comment]
CC-BY would be awesome, but also CC-BY-SA (or even CC-BY-SA-NC if you must).

**Comment by runjak** [comment]
As given by [wiki.creativecommons.org/FAQ](https://wiki.creativecommons.org/FAQ#Can_I_use_a_Creative_Commons_license_for_software.3F)  it is discouraged to use CC licenses for software, because in contrast to typical software licenses the CC licenses use more general legal terms and don't mention the distribution of source code.

To stick with a spirit of openness I'd recommend using the [MIT license](http://choosealicense.com/licenses/mit/), which is very permissive.

I've also found [choosealicense.com](http://choosealicense.com/) to be a good source to make license choices simple.

**Comment by ThomasK81** [comment]
Deal.
