### ISSUE TITLE
Question about file URNs

### ISSUE THREAD

**Issue by runjak** [runjak/TranscriptionDesk#15]
There is an Omeka item with the URN ```urn:cite:ogl:bnf_7989```.
All files belonging to this item have a filename like ```DigitalPetronius/urn_cite_ogl_bnf_7989/bnf_lat7989_195.jpeg```.
I presume, that the URN for such a file would than be ```urn:cite:ogl:bnf_lat7989_239.jpeg```?

The tricky thing here is that ```bnf_7989``` is not a prefix of ```bnf_lat7989_239.jpeg``` as I originally expected.
Since the files themselfs don't carry URNs in Omeka, we have to derive their URNs by combining the file names and the URNs of their items.

While we've had good [discussions](https://github.com/runjak/TranscriptionDesk/blob/master/notes/2015-07-10.md) about the layout of our own URNs,
we haven't touched the issue of file URNs so far.
What would be the expected way to generate URNs for files?

**Comment by ThomasK81** [comment]
Good spotting. It's fixed. 

If you have a URN urn:cite:ogl:bnf_lat7989 the directory name will be the same, but the colons will be replaced with underscores; the filename will be the last element of the urn + underscore + numerical element. If this is not the case, I made a mistake. :) 

 Does this answer the question?

**Comment by runjak** [comment]
Yes, that's perfect :)
This way I can test if the last part of the URN of an item is a correct prefix of the filename with ```_``` substituted for ```:```. If it is not, such cases can be reported as errors and will not be used in our database, until changed.

**Comment by runjak** [comment]
There are some cases where the files are named with ':' instead of '_' inside them:

        urn:cite:ogl:bern_bongIV665  doesn't yield URN for file bern:bongIV665:11v.tif
        urn:cite:ogl:bern_bongIV665  doesn't yield URN for file bern:bongIV665:12r.tif
        urn:cite:ogl:bern_bongIV665  doesn't yield URN for file bern:bongIV665:12v.tif
        urn:cite:ogl:bern_bongIV665  doesn't yield URN for file bern:bongIV665:13r.tif
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:1.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:2.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:3.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:4.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:5.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:6.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:7.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:8.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:9.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:10.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:11.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:12.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:13.jpeg
        urn:cite:ogl:dresd_dc141 doesn't yield URN for file Dresd:dc141:14.jpeg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:1r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:1v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:2r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:2v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:3r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:3v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:4r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:4v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:5r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:5v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:6r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:6v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:7r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:7v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:8r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:8v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:9r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:9v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:10r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:10v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:11r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:11v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:12r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:12v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:13r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:13v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:14r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:14v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:15r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:15v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:16r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:16v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:17r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:17v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:18r.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25:18v.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25IntrA.jpg
        urn:cite:ogl:plu37_25 doesn't yield URN for file Plut37:25IntrB.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:128r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:128v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:129r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:129v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:130r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:130v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:131r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:131v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:132r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:132v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:133r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:133v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:134r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:134v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:135r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:135v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:136r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:136v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:137r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:137v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:138r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:138v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:139r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:139v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:140r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:140v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:141r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:141v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:142r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:142v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:143r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:143v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:144r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:144v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:145r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:145v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:146r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:146v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:147r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:147v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:148r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:148v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:149r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:149v.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:150r.jpg
        urn:cite:ogl:plut47_31 doesn't yield URN for file Plut47:31:150v.jpg

In these cases I will map the ':' in the files to '_', so that the URN for the last one would read ```urn:cite:ogl:Plut47_31_150v.jpg```. It also appears that some file names start with an uppercase letter, instead of a lower case as would be expected. Compare ```plut47_31``` and ```Plut47:31:150v.jpg```. Should I map letters to lowercase in general or are these both cases that should be fixed in the input data?

**Comment by runjak** [comment]
Ah, my bad. The mentioned files don't have ':' in them - that was an error on my side, I believe. Going to verify that. The uppercase filenames are still a thing tough.

**Comment by runjak** [comment]
Ok, sorry for the long comments, but I'll do this again:

        'urn:cite:ogl:bern_bongIV665 ' doesn't yield URN for file bern_bongIV665_11v.tif
        'urn:cite:ogl:bern_bongIV665 ' doesn't yield URN for file bern_bongIV665_12r.tif
        'urn:cite:ogl:bern_bongIV665 ' doesn't yield URN for file bern_bongIV665_12v.tif
        'urn:cite:ogl:bern_bongIV665 ' doesn't yield URN for file bern_bongIV665_13r.tif
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_1.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_2.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_3.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_4.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_5.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_6.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_7.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_8.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_9.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_10.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_11.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_12.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_13.jpeg
        'urn:cite:ogl:dresd_dc141' doesn't yield URN for file Dresd_dc141_14.jpeg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_1r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_1v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_2r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_2v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_3r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_3v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_4r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_4v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_5r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_5v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_6r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_6v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_7r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_7v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_8r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_8v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_9r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_9v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_10r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_10v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_11r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_11v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_12r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_12v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_13r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_13v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_14r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_14v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_15r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_15v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_16r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_16v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_17r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_17v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_18r.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25_18v.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25IntrA.jpg
        'urn:cite:ogl:plu37_25' doesn't yield URN for file Plut37_25IntrB.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_128r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_128v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_129r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_129v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_130r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_130v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_131r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_131v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_132r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_132v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_133r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_133v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_134r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_134v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_135r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_135v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_136r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_136v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_137r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_137v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_138r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_138v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_139r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_139v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_140r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_140v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_141r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_141v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_142r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_142v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_143r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_143v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_144r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_144v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_145r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_145v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_146r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_146v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_147r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_147v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_148r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_148v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_149r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_149v.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_150r.jpg
        'urn:cite:ogl:plut47_31' doesn't yield URN for file Plut47_31_150v.jpg

From this I see two problems:

1. Files starting with uppercase letters
2. URNs with trailing space

**Comment by runjak** [comment]
Something has changed, as the remaining issues are these:

    'urn:cite:ogl:bern_bongIV665 ' doesn't yield URN for file 'bern_bongIV665_13r.tif'
    'urn:cite:ogl:dresd_dc141' doesn't yield URN for file 'Dresd_dc141_14.jpeg'
    'urn:cite:ogl:plu37_25' doesn't yield URN for file 'Plut37_25IntrB.jpg'
    'urn:cite:ogl:plut47_31' doesn't yield URN for file 'Plut47_31_150v.jpg'
