### ISSUE TITLE
finishing project Report

### ISSUE THREAD

**Issue by FTeichmann** [runjak/TranscriptionDesk#18]
I'm still improving the project report, currently up to L240.

@runjak: please fill in L240 subsection with keywords (I will phrase that later) and look at %FIXME at L229

**Comment by FTeichmann** [comment]
todo: 
- Struktur der Datenbasis
- Produktfunktionen
- Projektverlauf
- aktueller Stand, vllt. überflüssig
- Zusammenfassung und Ausblick

**Comment by FTeichmann** [comment]
project report is finished, still needs a lot of proofreading and LaTeX improvement.

**Comment by runjak** [comment]
Cool story :)
I've noticed that @Oliver1989 is already making some small adjustments to it.

**Comment by Oliver1989** [comment]
I read the entire document for correctness and understanding, and made according adjustments. As far as I am concerned, one more person should re-read it now and then I would consider the project report finished. But I know @FTeichmann wanted to make more changes, now that I finally pushed my changes.

**Comment by runjak** [comment]
I'll read it, too.

**Comment by runjak** [comment]
Chapter 4, 'Produktfunktion' sollte eine Einleitung haben.
So ist das einfach eine Liste, die da ins Dokument gesetzt wird, aber den Lesefluss bricht.

**Comment by runjak** [comment]
@Oliver1989 es ist [das Script](http://www.duden.de/rechtschreibung/Skript) daher korrigiere ich `einen PHP Script …, der Daten … sammelt` entsprechend .)

**Comment by runjak** [comment]
Ich bin mit dem Text bis auf Kapitel 4 zufrieden.
Ich fände es nett, wenn @RPOD hier noch eine Einleitung schaffen würde.

**Comment by RPOD** [comment]
Werde ich noch erledigen, allerdings ist es eher üblich kaum / keine Einleitung zu erstellen.

**Comment by runjak** [comment]
:sparkles: Wunderbar! :sparkles:

**Comment by RPOD** [comment]
@runjak habe sehr kurze Einleitung für Produktfunktionen geschrieben, lass mich wissen ob noch was hin soll oder nicht.

**Comment by FTeichmann** [comment]
Das ganze Kapitel sollte anders formatiert werden. @runjak schlägt Tabellen vor.

**Comment by runjak** [comment]
Die Einleitung sieht gut aus. Hab nach dem Telefonat mit @FTeichmann eben die Formatierung von Kapitel 4 geändert. Siehe f76f89358bfd706f2c5ff76143a6ffd66dfcd3f9

**Comment by runjak** [comment]
@RPOD hat mir mitgeteilt, dass ihn meine Änderungen nicht ausschließlich amüsieren, und wird sich dem nochmals annehmen.

**Comment by FTeichmann** [comment]
project report finished, good job everyone
