### ISSUE TITLE
Evaluating productfunctions

### ISSUE THREAD

**Issue by RPOD** [runjak/TranscriptionDesk#19]
In commit a10a5395791074fa5be523571d5c13734c106332 I added several product functions. I would like feedback if they are OK as they are, if some aren't needed etc. . Also within them there are a lot of ```underfull \hbox```. If this is a problem please let me know or resolve this issue.

**Comment by FTeichmann** [comment]
Functions look okay, I will spellcheck them later with the whole document.
discussion about formatting moved to #18
